name: Search for new version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  chocomilk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Play chocomilk
        uses: open-circle-ltd/chocomilk@master
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
          CHOCOLATEY_ITIGO_API_KEY: ${{ secrets.CHOCOLATEY_ITIGO_API_KEY }}
          CHOCOLATEY_ORG_API_KEY: ${{ secrets.CHOCOLATEY_ORG_API_KEY }}
          MATTERMOST_API_KEY: ${{ secrets.MATTERMOST_API_KEY }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          PWD: ${{ github.workspace }}
